from math import cos, sin, pi
import turtle as tortue

long = float(input())


print(cos(0) * long, sin(0) * long)
print(cos(pi/3) * long, sin(pi/3) * long)
print(cos(2 * pi/3) * long, sin(2 * pi/3) * long)
print(cos(pi) * long, sin(pi) * long)
print(cos(4 * pi/3) * long, sin(4 * pi/3) * long)
print(cos(5 * pi/3) * long, sin(5 * pi/3) * long)

tortue.up()
tortue.shape('turtle')
tortue.color('blue')
tortue.down()
tortue.goto(cos(0) * long, sin(0) * long)
tortue.goto(cos(pi/3) * long, sin(pi/3) * long)
tortue.goto(0, 0)
tortue.goto(cos(pi/3) * long, sin(pi/3) * long)
tortue.goto(cos(2 * pi/3) * long, sin(2 * pi/3) * long)
tortue.goto(0, 0)
tortue.goto(cos(2 * pi/3) * long, sin(2 * pi/3) * long)
tortue.goto(cos(pi) * long, sin(pi) * long)
tortue.goto(0, 0)
tortue.goto(cos(pi) * long, sin(pi) * long)
tortue.goto(cos(4 * pi/3) * long, sin(4 * pi/3) * long)
tortue.goto(0, 0)
tortue.goto(cos(4 * pi/3) * long, sin(4 * pi/3) * long)
tortue.goto(cos(5 * pi/3) * long, sin(5 * pi/3) * long)
tortue.goto(0, 0)
tortue.goto(cos(5 * pi/3) * long, sin(5 * pi/3) * long)
tortue.goto(cos(0) * long, sin(0) * long)
tortue.penup()
tortue.goto(0, -long)
tortue.pendown()
tortue.circle(long)
tortue.hideturtle()
tortue.done()